apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-non-root
  annotations:
    policies.kyverno.io/title: "Require Non-Root"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/category: "Pod Security"
    policies.kyverno.io/subject: "Pod"
    policies.kyverno.io/description: >-
      Enforce runAsNonRoot, readOnlyRootFilesystem, and drop ALL capabilities.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-security-context
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - kube-system
            - kyverno
            - falco
            - github-runners
            - dependency-track
            - monitoring
      validate:
        message: "Pod must run as non-root with read-only root filesystem and drop ALL capabilities."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
                  readOnlyRootFilesystem: true
                  capabilities:
                    drop:
                      - "ALL"
