apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: "Restrict Image Registries"
    policies.kyverno.io/severity: "critical"
    policies.kyverno.io/category: "Supply Chain Security"
    policies.kyverno.io/subject: "Pod"
    policies.kyverno.io/description: >-
      Only allow images from private Amazon ECR registries. Block DockerHub, Quay, GHCR.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-registries
      match:
        resources:
          kinds:
            - Pod
      exclude:
        resources:
          namespaces:
            - kube-system
            - kyverno
            - falco
            - github-runners
      validate:
        message: "Only private ECR registries are allowed."
        pattern:
          spec:
            containers:
              - image: "*.dkr.ecr.*.amazonaws.com/*"
